/** Re-export owner desk metrics for client tests (same logic as Edge). */

export {
  OWNER_FUNNEL_FEED_LIMIT,
  OWNER_FUNNEL_PAGE_SIZE,
  OWNER_FUNNEL_WINDOW_DAYS,
  OWNER_FUNNEL_WINDOW_LIMIT,
  assembleOwnerFunnelDeskFromServer,
  computeOwnerFunnelDeskMetrics,
  deskGetLinkRate,
  filterDeskReferrals,
  filterDeskShares,
  filterOwnerFunnelEvents,
  formatOwnerRate,
  inOwnerFunnelWindow,
  isDeskVerifiedShare,
  isEmptyOwnerFunnelDeskCounts,
  isIntentSharePlatform,
  isLockedReferrer,
  isOwnerFunnelAttributedLanding,
  isOwnerFunnelRpcMissingError,
  ownerFunnelWindowHasRows,
  ownerFunnelCutoffIso,
  ownerFunnelViaLabel,
  pageAllOwnerFunnelRows,
  parseOwnerFunnelDeskCounts,
  resolveOwnerFunnelDeskMetrics,
  resolveOwnerFunnelVia,
  stripOwnerFunnelPii,
  uniqueVisitorsForEvent,
  type OwnerFunnelDeskMetrics,
  type OwnerFunnelFeedRow,
  type OwnerFunnelVia,
} from '../../supabase/functions/_shared/owner-funnel-desk';

export {
  emptyOwnerFunnelGsc,
  formatGscCount,
  formatGscPosition,
  GSC_CACHED_NOTE,
  GSC_CONSOLE_URL,
  GSC_EDGE_SECRET_NAMES,
  GSC_MISSING_NOTE,
  GSC_PROPERTY,
  GSC_RESOLVE_TIMEOUT_MS,
  DESK_WINDOW_TIMEOUT_MS,
  GSC_TIMEOUT_NOTE,
  parseOwnerFunnelGsc,
  readGscServerSecret,
  readGscSiteUrl,
  rememberOkGsc,
  resetGscOkCache,
  resolveOwnerFunnelGsc,
  resolveOwnerFunnelGscTimed,
  withTimeout,
  type OwnerFunnelGscMetrics,
} from '../../supabase/functions/_shared/owner-funnel-gsc';
